---
title: "gender_display"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readr)
library(ggplot2)

options(scipen = 999)

gender_display <- read_csv(
  '../data/gender_display.csv')
```

## Demographic characteristics of the sample

# Gender
```{r}
gender_display %>%
  count(gender)

gender_display %>%
  ggplot(aes(x = gender)) +
  geom_bar()
```

#Femininetouch
```{r}
gender_display %>%
  xtabs(~ gender + Femininetouch, .)

chisq.test(
  gender_display$gender,
  gender_display$Femininetouch
)
```

#LwGazing
```{r}
gender_display %>%
  xtabs(~ gender + LwGazing, .)

chisq.test(
  gender_display$gender,
  gender_display$LwGazing
)
```

#LwWithdrawal
```{r}
gender_display %>%
  xtabs(~ gender + LwWithdrawal, .)

chisq.test(
  gender_display$gender,
  gender_display$LwWithdrawal
)
```

#LwCovering
```{r}
gender_display %>%
  xtabs(~ gender + LwCovering, .)

chisq.test(
  gender_display$gender,
  gender_display$LwCovering
)
```

#Bodydisplay
```{r}
Bodydisplay_median <- gender_display %>% group_by(gender) %>% summarise(Mdn = median(Bodydisplay))

Bodydisplay_median

gender_display %>%
  wilcox.test(
    Bodydisplay ~ gender,
    data = .
  )
```

#Ritulization
```{r}
Ritulization_median <- gender_display %>% group_by(gender) %>% summarise(Mdn = median(Ritulization))

Ritulization_median

gender_display %>%
  wilcox.test(
    Ritulization ~ gender,
    data = .
  )
```

gender_display <- gender_display %>%
  mutate(
    Female = gender == '2')

gender_display %>%
  ggplot(aes(x = Bodydisplay, fill = Female)) +
  geom_histogram(
    binwidth = 0.5)
    
gender_display %>%
  ggplot(aes(x = Ritulization, fill = Female)) +
  geom_histogram(
    binwidth = 0.5)    
    